# Generated by Django 4.1.1 on 2022-09-19 04:48

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MChat', '0003_alter_chatmessage_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='posted_on',
            field=timezone_field.fields.TimeZoneField(default='Asia/Dubai'),
        ),
    ]
