# Generated by Django 4.1.1 on 2022-09-19 04:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MChat', '0004_alter_chatmessage_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='posted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
